apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-deployment
  labels:
    app: person-app
spec:
  selector:
    matchLabels:
      app: person-app
  replicas: 1
  template:
    metadata:
      labels:
        app: person-app
    spec:
      containers:
        - name: person
          image: docker.io/fabianogoes/person:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: person-app-service
spec:
  type: NodePort
  selector:
    app: person-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
